### ISSUE TITLE
Can't pull the project to the repo under my github name 

### ISSUE THREAD

**Issue by Scorpion-rep** [SiddySixsmith/Game-Deal-Compare#13]
Hey Daniel, As I was working under the branch connected to the main branch under your name Sixsmith, I'm unable to pull it to my repo to deploy it on github

**Comment by SiddySixsmith** [comment]
very odd, I can see your branch on the site. A possible recommendation is to copy all work to an outside source and then get out of branch, create a new one and then add all new code then push.
